# Generated by Django 2.0.3 on 2019-12-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.CharField(default='', max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.CharField(default='', max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ingredients', models.CharField(default='', max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
