# Generated by Django 2.0.3 on 2019-12-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191201_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasta',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='salad',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
