# Generated by Django 2.0.3 on 2019-12-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191201_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price_large',
        ),
        migrations.AddField(
            model_name='pasta',
            name='has_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='has_large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salad',
            name='has_large',
            field=models.BooleanField(default=False),
        ),
    ]
