# Generated by Django 2.0.3 on 2019-12-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191201_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='ingredients',
            new_name='toppings',
        ),
    ]
