# Generated by Django 2.0.3 on 2019-12-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191201_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.CharField(default='', max_length=128),
        ),
    ]
