# Generated by Django 2.0.3 on 2019-12-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_cartitem_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='ordered',
            new_name='order_placed',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'orders'), ('model', 'pizza')), models.Q(('app_label', 'orders'), ('model', 'pasta')), models.Q(('app_label', 'orders'), ('model', 'salad')), models.Q(('app_label', 'orders'), ('model', 'notfood')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
