# Generated by Django 2.0.3 on 2019-12-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order_placed',
        ),
    ]
